server:
    port: [Porta Gerada do OnRender]

spring:
    datasource:
        url: jdbc:postgresql://dpg-cpf45cjtg9os73b79fag-a.oregon-postgres.render.com/bd_atv?user=bd_atv_user&password=DNrR2yW8z6ouIgYb7lHsk9HL1bSuzxFw
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    sql:
        init:
            schema-locations: classpath:schema-postgresql.sql
            mode: always
            platform: postgres

logging:
    level:
        root: INFO
        org.springframework: DEBUG
        org.hibernate: DEBUG
