server:
    port: [Porta Gerada do OnRender]

spring:
    datasource:
        url: jdbc:postgresql://[Hostname].oregon-postgres.render.com/[Database]?user=[Usename]&password=[Password]
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    sql:
        init:
            schema-locations: classpath:schema-postgresql.sql
            mode: always
            platform: postgres

logging:
    level:
        root: INFO
        org.springframework: DEBUG
        org.hibernate: DEBUG
